### ISSUE TITLE
a bit of clunky behaviour

### ISSUE THREAD

**Issue by kukoman** [VersatilityWerks/jTimeout#1]
Hi Shane,

excellent library I must say. Would you consider one more additional function/property? 
Although I understand that resetting the timeout count by mouse is kind of cool but it's really confusing for a new user. When my session times out, I come back and naturally I want to click the alert button. What happens however is it goes away and "I don't know" what happened, I didn't even had the time to read it because it disappeared immediately after I moved my mouse :(
as quick workaround I changed the if statement in the mousemove event:

```
if (!jTimeout.mouseMoved && ($('#jTimeoutAlert').length == 0 && $('#jTimedoutAlert').length == 0)) {
```

Now it triggers only when one of the windows are not rendered.
Would you consider adding one more property or changing the behaviour? 

thank you for you excellent work

**Comment by HTMLGuyLLC** [comment]
Of course. I'll add this when I have time.

**Comment by kukoman** [comment]
would you like to keep the original behaviour as default or can I propose the new behaviour as default and add boolean property to change it if needed?

**Comment by HTMLGuyLLC** [comment]
It should be a property with a toggle.
