### ISSUE TITLE
It really starts when I click inside the website

### ISSUE THREAD

**Issue by DanielZambranoC** [VersatilityWerks/jTimeout#13]
This only appears when I click the website

`onPriorCallback: function(jTimeout){
				    //tell them they will be timing out soon!
				    //to get the current time:
				    var secondsLeft = jTimeout.getTimer();
				    console.log('You will be timed out in: '+secondsLeft+' seconds');
				}`

seems like to be not working on ready 

`$2(function(){
			   $2.jTimeout({ `

**Comment by HTMLGuyLLC** [comment]
You're really not giving me much to go by here. What browser? Are you talking about specifically? The onPriorCallback? Does the timer countdown the entire time?  Are there any console errors? How do you know it's not working till you click? 

Please be more specific about the scenario.
