### ISSUE TITLE
jAlerts are not closed in other tabs

### ISSUE THREAD

**Issue by Mathieu265** [VersatilityWerks/jTimeout#14]
Not sure if it's my implementation that is wrong but when I click extend my session in one tab the jAlert stays open in the other tabs but the countdown is resetter correctly.

I changed this bit of code in my implementation
```
hideCountdownAlert: function()
            {
                timeout.timeoutWarning = false;

                var timeoutAlert = $('.jAlert');

                if (timeoutAlert.length > 0)
                {
                    timeoutAlert.closeAlert();
                }
            },
```
Don't know if it's a correct fix or my implementation is wrong, let me know.

**Comment by Mathieu265** [comment]
@VersatilityWerks

**Comment by HTMLGuyLLC** [comment]
The alert should hide when you return to another tab by default, but it's not necessarily ideal. What you've done is also not ideal. When I get a chance, I'll come up with a better solution.

**Comment by HTMLGuyLLC** [comment]
BTW, biggest issue with your solution is that it just removes whatever alert happens to be showing.
