### ISSUE TITLE
Version + NPM questions

### ISSUE THREAD

**Issue by designosis** [VersatilityWerks/jTimeout#15]
Hey,
This is the very best timeout implementation I've seen, thank you!
I do have two suggestions:

1) On the code page it says version is 3, however the `src` and `dist` content all says 2.1
2) Register jTimeout on NPM, so I can easily see whenever you submit a new release :)

Thanks again.

**Comment by HTMLGuyLLC** [comment]
Cool, will do. Thank you.

**Comment by HTMLGuyLLC** [comment]
WAY better version just released and added to NPM
