### ISSUE TITLE
Removing the modal on another tab after extending session

### ISSUE THREAD

**Issue by ngoduykhanh** [VersatilityWerks/jTimeout#25]
Hi,

Thanks for the great works. I am gonna integrate your lib to may application, using custom modal not jAlert. Everything looks good except when I have multiple tab and click on "exntend session" button:

Current tab:
- title flashing is stopped
- modal is closed

Another tab:
- title flashing is stopped
- modal is NOT closed.

Do you have any idea how to close the modal on another tab? I was looking for closing it on `onClickExtend` event, but it seems like it never been called.

Thanks

**Comment by abezulski** [comment]
I think I've hit the same problem when not using jAlert. Did you manage to find a workaround? #27

**Comment by ngoduykhanh** [comment]
Hi @abezulski , 

I had a workaround for my use case. In the `onClickExtend ` event, I used [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) to tell other tabs to close the Modal.
