### ISSUE TITLE
Reset after onTimeout alert is shown

### ISSUE THREAD

**Issue by Hamaada** [VersatilityWerks/jTimeout#7]
Hi,

Thanks for the nice plugins.
I am displaying the loginurl in an iframe, once the user logs in I call the reset() function to restart the loop which shows the default onPriorCallback alert but keeps counting below zero and never displays the onTimeout again

How can I restart the countdown loop again after onTimeout has been shown?

Thanks

**Comment by HTMLGuyLLC** [comment]
var timeout = $.jTimeout(options);
timeout.setTimer(x); //x=your session timeout length

**Comment by Hamaada** [comment]
It says setTimer is not a function, here's my code:

On the main page:
```
jQuery(document).ready(function() {
	
		jQuery.jTimeout({
			'timeoutAfter': 10,
			'secondsPrior': 5,
			'flashTitleSpeed': 1000,
			'extendUrl': SSOpage,
			'loginUrl': SSOpage,
			'extendOnMouseMove': false
			,
			'onTimeout': function(jTimeout){
				
				/* Alert User */
				jQuery.jAlert({
					'id': 'expiredAlert',
					'title': 'Your session has timed out. Please Sign On.',
					'theme': 'red',
					'iframe': SSOpage,
					'iframeHeight': '500px',
					'size': 'lg',
					'closeOnClick': false,
					'closeBtn': false,
					'closeOnEsc': false,
					'replaceOtherAlerts': true
				});
		});
});
```


Once the user logs in from the iframe I call this function: parent.resetTimeout();

```
function resetTimeout() {
		jQuery('#expiredAlert').closeAlert();

		var timeout = jQuery.jTimeout(options);
		timeout.setTimer(10); //session timeout length
	}
```

**Comment by HTMLGuyLLC** [comment]
That's not what I meant...that was a sample, not what you should use. 

More like this:

```
var mytimeout;
jQuery(document).ready(function() {
	
		mytimeout = jQuery.jTimeout({
			'timeoutAfter': 10,
			'secondsPrior': 5,
			'flashTitleSpeed': 1000,
			'extendUrl': SSOpage,
			'loginUrl': SSOpage,
			'extendOnMouseMove': false
			,
			'onTimeout': function(jTimeout){
				
				/* Alert User */
				jQuery.jAlert({
					'id': 'expiredAlert',
					'title': 'Your session has timed out. Please Sign On.',
					'theme': 'red',
					'iframe': SSOpage,
					'iframeHeight': '500px',
					'size': 'lg',
					'closeOnClick': false,
					'closeBtn': false,
					'closeOnEsc': false,
					'replaceOtherAlerts': true
				});
		});
});
```

and then

```
function resetTimeout() {
		jQuery('#expiredAlert').closeAlert();

		mytimeout.setTimer(10); //session timeout length
	}
```

10 is super low btw....

**Comment by Hamaada** [comment]
Almost there...
I had to add **mytimeout.timedOut = false;** for it to work, but when there's multiple tabs with the login iframe open, I need the other tabs' iframes to dissapear once I login in one of them

**Comment by HTMLGuyLLC** [comment]
That will require some custom code. Maybe after you popup the iframe, you start an interval that watches the timer and when it goes above 0, it hides the iframe.

```
window.setInterval(function(){
   if( mytimeout.getTimer() > 0 )
   {
         //hide iframe
   }
});
```

**Comment by Hamaada** [comment]
Modified it a bit and got this to work, thanks:
```
window.setInterval(function(){
if( window.localStorage.getItem('timeoutCountdown') > 0 && jQuery('#jTimedoutAlert:visible').length > 0 ){
jQuery('#jTimedoutAlert').closeAlert();
mytimeout.timedOut = false;
		}	
}, 1000);
```

**Comment by HTMLGuyLLC** [comment]
:thumbsup:

**Comment by evannitin** [comment]
Thanks in advance.
But i am facing the problem when i open multiple tabs and session time out then popup showing login again then i clicked on one opened tab on Login again. then another tab showing the popup with timer on another tabs.   
Please help this presist in the demo code which you have provided
Thanks

**Comment by HTMLGuyLLC** [comment]
1) Please do not comment on closed issues. If you have an issue, please create a new one.
2) I cannot replicate this. I opened several tabs of the demo, clicked "Timed out" on one, went to all of them and they showed the popup, then clicked "reset" and they all had the popup hide automatically.
