### ISSUE TITLE
localStorage issue with IE Edge on windows 10

### ISSUE THREAD

**Issue by Hamaada** [VersatilityWerks/jTimeout#9]
Hi again,

Was testing for my project on IE Edge on windows 10, looks like localStorage doesn't work!

**Comment by HTMLGuyLLC** [comment]
Interesting. That will require a patch then. Can you please integrate this: https://github.com/mortzdk/localStorage

**Comment by Hamaada** [comment]
That library didn't work.

It seems that Edge sets and update the values correctly in local Storage expect for the timeoutCountdown,

The countdown works on the latest tab but isn't sync'd across other tabs.

**Comment by HTMLGuyLLC** [comment]
Hmmm, yea...it probably switches to using cookies or something on IE10 then. The only way the timeout countdown will work is if the data is shared across all the tabs. Hmmmm...any ideas? I built this for a CRM for a client and then continued using it in other internal software so browser support has never really been a big concern. I would like to tackle this.

**Comment by HTMLGuyLLC** [comment]
See if this is your problem please http://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10/20848924#20848924

**Comment by Hamaada** [comment]
No, I don't get any access denied, actually the values are updated and sync'd correctly for timeoutTabLast and timeoutTab.

Only timeoutCountdown isn't sync'd, the priorCountDown timer works on the last active tab only.

**Comment by HTMLGuyLLC** [comment]
Crazy. It doesn't sound consistent enough to be able to track down the problem lol.

**Comment by Hamaada** [comment]
Good news, ran another test on Edge version 38, EdgeHTML 14.xx and it works

The other one Edge 25, EdgeHTML 13.xx doesn't work (was on my company pc's, should be upgraded)

Thanks for helping

**Comment by HTMLGuyLLC** [comment]
Oh excellent!! Thanks for letting me know!
